apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-Joe3
spec:
  displayName: Theme Joe3
  author:
    name: Jiewenhuang
    website: 'https://halo.run'
  description: Halo2.0主题 Joe3
  logo: 'https://wmimg.com/i/70/2023/08/64d3c41d5bde2.webp'
  website: 'https://www.jiewen.run'
  repo: 'https://github.com/jiewenhuang/halo-theme-joe3.0'
  settingName: 'theme-Joe-setting'
  configMapName: 'theme-Joe-configMap'
  version: '1.4.0'
  require: '>=2.19.0'
  customTemplates:
    post:
      - name: 链接跳转
        description: 链接跳转
        screenshot: 
        file: reverie/jump_link.html
    page:
      - name: 留言板
        description: 留言板文章
        screenshot:
        file: page_leaving.html
      - name: 友链
        description: 友链模板
        screenshot:
        file: page_links.html
      - name: Memos
        description: Memos
        screenshot:
        file: reverie/memos_display.html
      - name: 随手拍
        description: Memos相册页面
        screenshot:
        file: reverie/memos_photos.html
      - name: 时间轴/里程碑
        description: 里程碑页面
        screenshot:
        file: reverie/time_line.html
      - name: 相册
        description: 相册页面
        screenshot:
        file: photos.html
      - name: 朋友圈
        description: 朋友圈页面
        screenshot:
        file: friends.html
      - name: 音乐播放器
        description: 音乐播放页面
        screenshot:
        file: reverie/music_player.html

